## Visual Assessment: Acquaint Yourself
This Auralin Phase II clinical trial dataset comes in three tables: `patients`, `treatments`, and `adverse_reactions`. Acquaint yourself with them through visual assessment below.

### Gather

In [1]:
import pandas as pd

In [2]:
patients = pd.read_csv('patients.csv')
treatments = pd.read_csv('treatments.csv')
adverse_reactions = pd.read_csv('adverse_reactions.csv')

### Assess
In the cells below, each column of each table in this clinical trial dataset is described. To see the table that goes hand in hand with these descriptions, display each table in its entirety by displaying the pandas DataFrame that it was gathered into. This task is the mechanical part of visual assessment in pandas.

In [3]:
# Display the patients table
patients.T

,0,1,2,3,4,5,6,7,8,9,...,493,494,495,496,497,498,499,500,501,502
patient_id,1,2,3,4,5,6,7,8,9,10,...,494,495,496,497,498,499,500,501,502,503
assigned_sex,female,female,male,male,male,male,female,female,male,female,...,female,female,male,male,male,male,male,female,female,male
given_name,Zoe,Pamela,Jae,Liêm,Tim,Rafael,Mary,Xiuxiu,Dsvid,Sophie,...,Fen,Sirkka,Hajime,Alexander,Masataka,Mustafa,Ruman,Jinke,Chidalu,Pat
surname,Wellish,Hill,Debord,Phan,Neudorf,Costa,Adams,Chang,Gustafsson,Cabrera,...,Chin,Piirainen,Tsukada,Hueber,Murakami,Lindström,Bisliev,de Keizer,Onyekaozulu,Gersten
address,576 Brown Bear Drive,2370 University Hill Road,1493 Poling Farm Road,2335 Webster Street,1428 Turkey Pen Lane,1140 Willis Avenue,3145 Sheila Lane,2687 Black Oak Hollow Road,1790 Nutter Street,3303 Anmoore Road,...,1826 Poplar Chase Lane,4102 Ritter Avenue,4111 Thunder Road,3868 Freed Drive,1179 Patton Lane,2530 Victoria Court,494 Clarksburg Park Road,649 Nutter Street,3652 Boone Crockett Lane,2778 North Avenue
city,Rancho California,Armstrong,York,Woodbridge,Dothan,Daytona Beach,Burbank,Morgan Hill,Kansas City,New York,...,Boise,Roseville,San Mateo,Stockton,Tulsa,Milton Mills,Sedona,Overland Park,Seattle,Burr
state,California,Illinois,Nebraska,NJ,AL,Florida,NV,CA,MO,New York,...,ID,MI,CA,California,OK,ME,AZ,MO,WA,Nebraska
zip_code,92390,61812,68467,7095,36303,32114,84728,95037,64105,10011,...,83702,48066,94403,95204,74116,3852,86341,64110,98109,68324
country,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States,...,United States,United States,United States,United States,United States,United States,United States,United States,United States,United States
contact,951-719-9170ZoeWellish@superrito.com,PamelaSHill@cuvox.de+1 (217) 569-3204,402-363-6804JaeMDebord@gustr.com,PhanBaLiem@jourrapide.com+1 (732) 636-8246,334-515-7487TimNeudorf@cuvox.de,386-334-5237RafaelCardosoCosta@gustr.com,775-533-5933MaryBAdams@einrot.com,XiuxiuChang@einrot.com1 408 778 3236,816-265-9578DavidGustafsson@armyspy.com,SophieCabreraIbarra@teleworm.us1 718 795 9124,...,FenChin@gustr.com+1 (208) 388-1065,SirkkaPiirainen@teleworm.us+1 (586) 790-0975,650-570-4896HajimeTsukada@dayrep.com,AlexanderHueber@jourrapide.com1 209 762 2320,MasatakaMurakami@einrot.com+1 (918) 984-9171,207-477-0579MustafaLindstrom@jourrapide.com,928-284-4492RumanBisliev@gustr.com,816-223-6007JinkedeKeizer@teleworm.us,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,PatrickGersten@rhyta.com402-848-4923
birthdate,7/10/1976,4/3/1967,2/19/1980,7/26/1951,2/18/1928,8/31/1931,11/19/1969,8/13/1958,3/6/1937,12/3/1930,...,3/18/1997,1/16/1942,9/5/1972,9/12/1942,8/19/1937,4/10/1959,3/26/1948,1/13/1971,2/13/1952,5/3/1954
weight,121.7,118.8,177.8,220.9,192.3,183.9,146.3,158,163.9,194.7,...,195.1,126.3,168.1,194,155.1,181.1,239.6,171.2,176.9,138.2
height,66,66,71,70,27,70,65,60,66,64,...,68,67,66,72,72,72,70,67,67,71
bmi,19.6,19.2,24.8,31.7,26.1,26.4,24.3,30.9,26.5,33.4,...,29.7,19.8,27.1,26.3,21,24.6,34.4,26.8,27.7,19.3

`patients` columns:
- **patient_id**: the unique identifier for each patient in the [Master Patient Index](https://en.wikipedia.org/wiki/Enterprise_master_patient_index) (i.e. patient database) of the pharmaceutical company that is producing Auralin
- **assigned_sex**: the assigned sex of each patient at birth (male or female)
- **given_name**: the given name (i.e. first name) of each patient
- **surname**: the surname (i.e. last name) of each patient
- **address**: the main address for each patient
- **city**: the corresponding city for the main address of each patient
- **state**: the corresponding state for the main address of each patient
- **zip_code**: the corresponding zip code for the main address of each patient
- **country**: the corresponding country for the main address of each patient (all United states for this clinical trial)
- **contact**: phone number and email information for each patient
- **birthdate**: the date of birth of each patient (month/day/year). The [inclusion criteria](https://en.wikipedia.org/wiki/Inclusion_and_exclusion_criteria) for this clinical trial is  age >= 18 *(there is no maximum age because diabetes is a [growing problem](http://www.diabetes.co.uk/diabetes-and-the-elderly.html) among the elderly population)*
- **weight**: the weight of each patient in pounds (lbs)
- **height**: the height of each patient in inches (in)
- **bmi**: the Body Mass Index (BMI) of each patient. BMI is a simple calculation using a person's height and weight. The formula is BMI = kg/m<sup>2</sup> where kg is a person's weight in kilograms and m<sup>2</sup> is their height in metres squared. A BMI of 25.0 or more is overweight, while the healthy range is 18.5 to 24.9. *The [inclusion criteria](https://en.wikipedia.org/wiki/Inclusion_and_exclusion_criteria) for this clinical trial is 16 >= BMI >= 38.*

In [4]:
# Display the treatments table
treatments

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
5,jasmine,sykes,-,42u - 44u,7.56,7.18,0.38
6,sophia,haugen,37u - 42u,-,7.65,7.27,0.38
7,eddie,archer,31u - 38u,-,7.89,7.55,0.34
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
11,kristiina,hyypiä,-,36u - 38u,7.87,7.49,0.38
12,roxanne,andreyeva,29u - 38u,-,9.54,9.14,NaN
13,gregor,bole,-,47u - 45u,7.61,7.16,0.95
14,simone,baumgaertner,27u - 37u,-,7.74,7.30,NaN
15,enco,žibrik,55u - 68u,-,7.78,7.34,NaN
16,camilla,zaitseva,28u - 37u,-,7.53,7.13,NaN
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
18,addolorata,lombardi,-,49u - 46u,7.75,7.33,NaN
19,khalid,johnsrud,-,54u - 54u,8.35,7.94,NaN
20,mile,stanić,-,47u - 48u,7.66,7.24,0.92
21,tekla,walczak,29u - 39u,-,7.61,7.29,0.32
22,brancaleone,russo,53u - 60u,-,8.61,8.18,NaN
23,chiemela,tobeolisa,-,43u - 47u,7.59,7.17,NaN
24,isac,berg,31u - 41u,-,9.68,9.29,0.39
25,benoît,bonami,-,44u - 43u,9.82,9.40,0.92
26,suhaim,rahal,-,49u - 47u,7.94,7.50,0.94
27,mizuki,iwata,-,45u - 46u,7.70,7.23,0.97
28,clinton,miller,42u - 51u,-,7.79,7.40,0.39
29,eugene,mironov,42u - 49u,-,7.81,7.48,0.33
...,...,...,...,...,...,...,...
250,chen,yao,-,56u - 57u,7.90,7.51,0.39
251,aksel,vestergaard,-,42u - 38u,9.62,9.29,NaN
252,ellen,luman,-,40u - 39u,9.27,8.77,0.50
253,albino,schiavone,35u - 43u,-,7.56,7.15,NaN
254,jose,combs,-,39u - 36u,7.89,7.42,NaN
255,jia li,teng,48u - 54u,-,7.66,7.32,0.34
256,ilija,horvat,42u - 50u,-,7.77,7.38,0.39
257,mathilde,nørgaard,-,27u - 28u,8.50,8.10,0.90
258,csilla,herczegh,-,43u - 46u,7.71,7.27,NaN
259,aaliyah,rice,-,31u - 31u,7.64,7.33,0.31
260,david,beauvais,-,26u - 23u,7.87,7.47,NaN
261,caroline,shuler,-,50u - 54u,7.63,7.27,NaN
262,alex,crawford,51u - 62u,-,7.69,7.30,0.39
263,rebecca,jephcott,53u - 63u,-,7.96,7.57,0.39
264,chukwumoge,ogochukwu,-,41u - 39u,7.95,7.56,0.39
265,fearne,mcgregor,-,27u - 29u,7.83,7.48,0.35
266,ursula,freud,42u - 54u,-,7.75,7.46,0.29
267,leon,scholz,-,38u - 32u,7.72,7.29,0.93
268,yasmin,araujo,-,51u - 54u,7.82,7.36,0.96
269,hiromu,horikawa,-,47u - 46u,7.77,7.28,NaN
270,mika,martinsson,34u - 43u,-,7.50,7.17,0.33
271,leo,vieira,-,30u - 33u,7.74,7.36,NaN
272,steven,roy,-,41u - 43u,7.87,7.43,0.94
273,kate,wilkinson,36u - 39u,-,7.72,7.20,NaN
274,naja,enoksen,43u - 50u,-,7.98,7.59,NaN
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN
277,mathea,lillebø,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samúel,guðbrandsson,53u - 56u,-,8.00,7.64,0.36

350 patients participated in this clinical trial. None of the patients were using Novodra (a popular injectable insulin) or Auralin (the oral insulin being researched) as their primary source of insulin before.  All were experiencing elevated HbA1c levels.

All 350 patients were treated with Novodra to establish a baseline HbA1c level and insulin dose. After four weeks, which isn’t enough time to capture all the change in HbA1c that can be attributed by the switch to Auralin or Novodra:
- 175 patients switched to Auralin for 24 weeks
- 175 patients continued using Novodra for 24 weeks

`treatments` columns:
- **given_name**: the given name of each patient in the Master Patient Index that took part in the clinical trial
- **surname**: the surname of each patient in the Master Patient Index that took part in the clinical trial
- **auralin**: the baseline median daily dose of insulin from the week prior to switching to Auralin (the number before the dash) *and* the ending median daily dose of insulin at the end of the 24 weeks of treatment measured over the 24th week of treatment (the number after the dash). Both are measured in units (shortform 'u'), which is the [international unit](https://en.wikipedia.org/wiki/International_unit) of measurement and the standard measurement for insulin.
- **novodra**: same as above, except for patients that continued treatment with Novodra
- **hba1c_start**: the patient's HbA1c level at the beginning of the first week of treatment. HbA1c stands for Hemoglobin A1c. The [HbA1c test](https://depts.washington.edu/uwcoe/healthtopics/diabetes.html) measures what the average blood sugar has been over the past three months. It is thus a powerful way to get an overall sense of how well diabetes has been controlled. Everyone with diabetes should have this test 2 to 4 times per year. Measured in %.
- **hba1c_end**: the patient's HbA1c level at the end of the last week of treatment
- **hba1c_change**: the change in the patient's HbA1c level from the start of treatment to the end, i.e., `hba1c_start` - `hba1c_end`. For Auralin to be deemed effective, it must be "noninferior" to Novodra, the current standard for insulin. This "noninferiority" is statistically defined as the upper bound of the 95% confidence interval being less than 0.4% for the difference between the mean HbA1c changes for Novodra and Auralin (i.e. Novodra minus Auralin).

In [5]:
# Display the adverse_reactions table
adverse_reactions

     given_name     surname           adverse_reaction
0         berta  napolitani  injection site discomfort
1          lena        baer               hypoglycemia
2        joseph         day               hypoglycemia
3        flavia  fiorentino                      cough
4       manouck     wubbels          throat irritation
5       jasmine       sykes               hypoglycemia
6        louise     johnson               hypoglycemia
7       albinca     komavec               hypoglycemia
8           noe      aranda               hypoglycemia
9         sofia   hermansen  injection site discomfort
10        tegan     johnson                   headache
11         abel     yonatan                      cough
12    abdul-nur         isa               hypoglycemia
13         leon      scholz  injection site discomfort
14     gabriele     saenger               hypoglycemia
15       jia li        teng                     nausea
16        jakob    jakobsen               hypoglycemia
17  christopher    woodward                     nausea
18          ole    petersen               hypoglycemia
19       finley    chandler                   headache
20     anenechi       chidi               hypoglycemia
21     miłosław  wiśniewski  injection site discomfort
22        lixue       hsueh  injection site discomfort
23        merci      leroux               hypoglycemia
24         kang         mai  injection site discomfort
25       elliot  richardson               hypoglycemia
26      clinton      miller          throat irritation
27       idalia       moore               hypoglycemia
28       xiuxiu       chang               hypoglycemia
29         alex    crawford               hypoglycemia
30       monika      lončar               hypoglycemia
31       steven         roy                   headache
32      cecilie      nilsen               hypoglycemia
33    krisztina      magyar               hypoglycemia

`adverse_reactions` columns:
- **given_name**: the given name of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
- **surname**: the surname of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
- **adverse_reaction**: the adverse reaction reported by the patient

Additional useful information:
- [Insulin resistance varies person to person](http://www.tudiabetes.org/forum/t/how-much-insulin-is-too-much-on-a-daily-basis/9804/5), which is why both starting median daily dose and ending median daily dose are required, i.e., to calculate change in dose.
- It is important to test drugs and medical products in the people they are meant to help. People of different age, race, sex, and ethnic group must be included in clinical trials. This [diversity](https://www.clinicalleader.com/doc/an-fda-perspective-on-patient-diversity-in-clinical-trials-0001) is reflected in the `patients` table.
- Ensuring column names are descriptive enough is an important step in acquainting yourself with the data. 'Descriptive enough' is subjective. Ideally you want short column names (so they are easier to type and read in code form) but also fully descriptive. Length vs. descriptiveness is a tradeoff and common debate (a [similar debate](https://softwareengineering.stackexchange.com/questions/176582/is-there-an-excuse-for-short-variable-names) exists for variable names). The *auralin* and *novodra* column names are probably not descriptive enough, but you'll address that later so don't worry about that for now.